@startuml
!include .\\DigitecContext.puml
!include .\\Models\Account.puml
!include .\\Models\Classe.puml
!include .\\Models\Student.puml
!include .\\Models\Transaction.puml
!include .\\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0\DAL.AssemblyInfo.puml
!include .\\obj\Debug\net8.0\DAL.GlobalUsings.g.puml
!include .\\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Release\net8.0\DAL.AssemblyInfo.puml
!include .\\obj\Release\net8.0\DAL.GlobalUsings.g.puml
@enduml
