@startuml
!include .\\DAL\SchoolContext.puml
!include .\\MVCProject\Program.puml
!include .\\WebAPINormal\Program.puml
!include .\\DAL\Models\Account.puml
!include .\\DAL\Models\Classe.puml
!include .\\DAL\Models\Student.puml
!include .\\DAL\Models\Transaction.puml
!include .\\MVCProject\Controllers\HomeController.puml
!include .\\MVCProject\Models\ErrorViewModel.puml
!include .\\MVCProject\Models\PrintRequestM.puml
!include .\\MVCProject\Models\StudentM.puml
!include .\\MVCProject\Models\TransactionM.puml
!include .\\MVCProject\Services\ISchoolServices.puml
!include .\\MVCProject\Services\SchoolServices.puml
!include .\\WebAPINormal\Controllers\StudentsController.puml
!include .\\WebAPINormal\Controllers\TransactionsController.puml
!include .\\WebAPINormal\Extension\ConverterExtensions.puml
!include .\\WebAPINormal\Models\PrintRequestM.puml
!include .\\WebAPINormal\Models\StudentM.puml
!include .\\WebAPINormal\Models\TransactionM.puml
!include .\\DAL\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\DAL\obj\Debug\net8.0\DAL.AssemblyInfo.puml
!include .\\DAL\obj\Debug\net8.0\DAL.GlobalUsings.g.puml
!include .\\DAL\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\DAL\obj\Release\net8.0\DAL.AssemblyInfo.puml
!include .\\DAL\obj\Release\net8.0\DAL.GlobalUsings.g.puml
!include .\\MVCProject\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MVCProject\obj\Debug\net8.0\MVCProject.AssemblyInfo.puml
!include .\\MVCProject\obj\Debug\net8.0\MVCProject.GlobalUsings.g.puml
!include .\\MVCProject\obj\Debug\net8.0\MVCProject.RazorAssemblyInfo.puml
!include .\\MVCProject\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MVCProject\obj\Release\net8.0\MVCProject.AssemblyInfo.puml
!include .\\MVCProject\obj\Release\net8.0\MVCProject.GlobalUsings.g.puml
!include .\\MVCProject\obj\Release\net8.0\MVCProject.RazorAssemblyInfo.puml
!include .\\WebAPINormal\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\WebAPINormal\obj\Debug\net8.0\WebAPINormal.AssemblyInfo.puml
!include .\\WebAPINormal\obj\Debug\net8.0\WebAPINormal.GlobalUsings.g.puml
!include .\\WebAPINormal\obj\Debug\net8.0\WebAPINormal.MvcApplicationPartsAssemblyInfo.puml
!include .\\WebAPINormal\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\WebAPINormal\obj\Release\net8.0\WebAPINormal.AssemblyInfo.puml
!include .\\WebAPINormal\obj\Release\net8.0\WebAPINormal.GlobalUsings.g.puml
@enduml
